name: Verify labels for release

on:
  pull_request_target:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@2f0319c23a61915af52e8f905cf7c272be3b363d #v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'bug, enhancement, maintenance'
          pull-request-number: '${{ github.event.pull_request.number }}'
